name: BookShelf
options:
  bundleIdPrefix: com.zachthomas
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
settings:
  SWIFT_VERSION: "5.9"
  TARGETED_DEVICE_FAMILY: "1,2"
  INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
  INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
  INFOPLIST_KEY_UILaunchScreen_Generation: YES
  INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
  INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
  GENERATE_INFOPLIST_FILE: YES
  CURRENT_PROJECT_VERSION: "1"
  MARKETING_VERSION: "1.0"
targets:
  BookShelf:
    type: application
    platform: iOS
    sources:
      - BookShelf
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.zachthomas.bookshelf
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
