name: BookShelf
options:
  bundleIdPrefix: com.zachthomas
  deploymentTarget:
    iOS: "17.0"
settings:
  DEVELOPMENT_TEAM: ""
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"
targets:
  BookShelf:
    type: application
    platform: iOS
    sources:
      - BookShelf
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.zachthomas.bookshelf
      INFOPLIST_GENERATION_MODE: GeneratedFile
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
      SWIFT_EMIT_LOC_STRINGS: YES
